name: 🐛 バグ報告
description: バグや問題の報告
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        バグ報告ありがとうございます。以下の情報を記入してください。

  - type: textarea
    id: bug-description
    attributes:
      label: バグの説明
      description: 発生した問題について説明してください
      placeholder: 例）demo.pyを実行するとエラーが発生する
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 再現手順
      description: バグを再現するための手順を記載してください
      placeholder: |
        1. demo.pyを実行する
        2. エラーが表示される
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 期待される動作
      description: 本来どのような動作をするべきかを説明してください
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 環境情報
      description: OS、Pythonバージョン、その他関連する環境情報
      placeholder: |
        - OS: Windows 11 / macOS 14 / Ubuntu 22.04
        - Python: 3.12.1
        - GPU: あり / なし
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: その他の情報
      description: エラーメッセージ、スクリーンショット、その他関連情報
    validations:
      required: false